### ISSUE TITLE
Enhance `edit` command

### ISSUE THREAD

**Issue by domlimm** [AY2122S2-CS2103-F11-2/tp#102]
To look at fields to allow for editing.

**Comment by domlimm** [comment]
Only these fields can be edited as discussed in meeting, caa 230322:
1. Phone (Present in `AB3` base)
2. Application Status (To KIV with @tiewweijian )
3. Availability (Done by @LeeEnEn )

**Comment by domlimm** [comment]
Linked to #196.

**Comment by charmainehly** [comment]
Adding the scope of checks that we might need to validify:
- [ ] 1. ensure that edits to student id updates the email (if applicable)
- [ ] 2. ensure student Id and emails are unique
- [ ] 3. ensure any changes to availability do not conflict with any existing upcoming interviews

**Comment by domlimm** [comment]
Thank you @charmainehly! 😄

**Comment by domlimm** [comment]
- [ ] When user edits candidate's `email`, check if `email` already exists

**Comment by domlimm** [comment]
To discuss with team, 

Flow:
`focus X`
`edit X id/AXXXXXXXA`

Focus panel does not show latest change, should we refresh? If so, how do we tell if `focus X` was actually executed?

**Comment by domlimm** [comment]
The feedback is incorrect. Honestly, a hassle to change it. Discussion

![image](https://user-images.githubusercontent.com/46486515/160579531-33e265ef-86d1-45f6-9c5c-b54eb3e4397b.png)
