### ISSUE TITLE
Fix naming conventions for InterviewSchedule

### ISSUE THREAD

**Issue by lzan98** [AY2122S2-CS2103-F11-2/tp#154]
Previously while implementing schedule function, the `InterviewSchedule` class was initially named as `InterviewList`, but was changed afterwards to avoid confusion. Hence there are a number of `InterviewSchedule` objects named as interviewList instead of interviewSchedule - a small documentation "bug" to fix, leaving this issue here in case I forget about it.

**Comment by tiewweijian** [comment]
I could do the simple refactoring !
