### ISSUE TITLE
Delete `Address` & `Tags` (including all related classes and usages)

### ISSUE THREAD

**Issue by charmainehly** [AY2122S2-CS2103-F11-2/tp#158]
- [ ] address
- [x] tags

**Comment by domlimm** [comment]
@charmainehly char, I think I could do it.

**Comment by tiewweijian** [comment]
@domlimm you got time? if not I could start on this once i finish the documentations

**Comment by charmainehly** [comment]
If we can't fit it in 1.3b, I believe its allowed for 1.4!!
