### ISSUE TITLE
Update `help` window content in GUI

### ISSUE THREAD

**Issue by charmainehly** [AY2122S2-CS2103-F11-2/tp#176]

**Comment by domlimm** [comment]
Char, I was thinking go fancy and make some beautiful rows for each command LOL. What ya think?

**Comment by charmainehly** [comment]
sure why not! i _think_ shouldnt be too tough! 👍

**Comment by domlimm** [comment]
i could help! unless you wanna do it 😛

**Comment by charmainehly** [comment]
Haha go for it!!! :) Will assign you 😛
