### ISSUE TITLE
Fix bug on candidate search under `find` command

### ISSUE THREAD

**Issue by charmainehly** [AY2122S2-CS2103-F11-2/tp#189]
Currently the `find` command for the `candidate` field is implemented by checking the `toString()` of each Candidate.

Introduces a bug where keywords like `availability` is included in the search.

To create a new method that searches through each of the candidates' fields instead.

**Comment by domlimm** [comment]
Hey @charmainehly, the `availability` portion has been handled. Maybe there's underlying bugs but I tested and it seemd to be ok for all. When you look into this, maybe you could test it out first please 😄 Let's discuss too!
