### ISSUE TITLE
Fix bugs relating to GUI display and window

### ISSUE THREAD

**Issue by charmainehly** [AY2122S2-CS2103-F11-2/tp#190]
To address all bugs with regards to default size when the GUI app is started, as well as how the display works with the minimisation of screens.

**Comment by domlimm** [comment]
Totally forgot about the minimising of the screens 😭 thanks @charmainehly!

**Comment by charmainehly** [comment]
tasks:
- [ ] deal with minimisation of screen - allow vertical and horizontal overflow scroll
- [ ] set preferred gui window size upon user's start up
- [ ] fix width of feedback box
- [ ] create summary of number of scheduled interview and number of candidates in system? (KIV)
