### ISSUE TITLE
Edit when `InterviewStatus` is `Completed`, Block Scheduling

### ISSUE THREAD

**Issue by tiewweijian** [AY2122S2-CS2103-F11-2/tp#201]
Currently, there is a loophole in our scheduling system. 

User scheduled interview
`Not Scheduled` —> `Scheduled` 

User finishes interview 
`Scheduled` —> `Completed`

User schedules another interview 
`Completed` —> `Scheduled` 

User deletes interview before the interview date 
`Scheduled` —> `Not Scheduled` 

So essentially, a user can change from `Completed` to `Not Scheduled`, which is not the intended purpose.

**Comment by domlimm** [comment]
💘
