### ISSUE TITLE
Display only important attributes in Candidate List

### ISSUE THREAD

**Issue by tiewweijian** [AY2122S2-CS2103-F11-2/tp#212]
In the Candidate List (left panel), only show important attributes such as `Name`, `StudentID`, `ApplicationStatus` and `InterviewStatus`

**Comment by domlimm** [comment]
thanks @tiewweijian!

**Comment by charmainehly** [comment]
@tiewweijian i think shld still have availability too? :O

**Comment by tiewweijian** [comment]
@charmainehly yes !! i missed that out ! thanks!
