### ISSUE TITLE
Add `remark` command

### ISSUE THREAD

**Issue by charmainehly** [AY2122S2-CS2103-F11-2/tp#218]
KIV - to attempt by tonight.

**Comment by charmainehly** [comment]
**Update on progress:** pending test cases to be created specific to the remark command

**Functionality of remark command:** the remark command is standalone from the `edit`, `add` or `delete` command. i.e. this implies that the user **cannot** modify a candidate's remark via the aforementioned three commands. A candidate has to -  
1. `Add` a new candidate to the system - any attempt to use the /r prefix will be invalid/not recognised
2. `Remark INDEX r/[REMARK]` to add a remark to an existing candidate with index `INDEX`. 
3. To futher modify or delete a candidate's remark in the future, the user has to use the same `Remark` command, but potentially leave the `[REMARK]` argument as empty (i.e. read as an empty string).

**Comment by domlimm** [comment]
LGTM on the workflow! 💯 Very smart re-using `add-remark-tutorial`!
