### ISSUE TITLE
Preliminary Testing before `v1.3b`

### ISSUE THREAD

**Issue by tiewweijian** [AY2122S2-CS2103-F11-2/tp#240]
Hi guys ! 

- Let's do some extensive testing before we submit our `v1.3b` ! 
- Let's try to clear and merge all outstanding PRs, and we can begin our testing on our local devices ! 
- Let's also report the bugs we discovered during this short iteration of testing in this thread. 

Thanks guys !!

**Comment by charmainehly** [comment]
minor discussion points:
1. restrict find command to accept only 1 field?
2. sort command - allow asc or desc?

**Comment by charmainehly** [comment]
Loading Data:
- [ ] if data loaded in has an empty string for `applicationStatus`, the tag does not show up.
- [ ] likewise with `interviewStatus`.

<img width="1196" alt="Screenshot 2022-03-30 at 4 44 04 PM" src="https://user-images.githubusercontent.com/65525578/160790268-bcf6e665-a3ea-4766-9359-6a27d5905a20.png">

**Comment by domlimm** [comment]
> Loading Data (see candidate at index 10:
> 
> * [ ]  if data loaded in has an empty string for `applicationStatus`, the tag does not show up.
> * [ ]  likewise with `interviewStatus`.
> 
> (ignore different coloured headers - not yet merged with latest pr standardising the ui) <img alt="Screenshot 2022-03-30 at 4 46 44 PM" width="1194" src="https://user-images.githubusercontent.com/65525578/160790838-6d995a0d-859a-48fa-a8a4-106554a1803f.png">

Should we wrap the text hmmm?

**Comment by charmainehly** [comment]
> > Loading Data (see candidate at index 10:
> > 
> > * [ ]   if data loaded in has an empty string for `applicationStatus`, the tag does not show up.
> > * [ ]   likewise with `interviewStatus`.
> > 
> > (ignore different coloured headers - not yet merged with latest pr standardising the ui) <img alt="Screenshot 2022-03-30 at 4 46 44 PM" width="1194" src="https://user-images.githubusercontent.com/65525578/160790838-6d995a0d-859a-48fa-a8a4-106554a1803f.png">
> 
> Should we wrap the text hmmm?

I'm thinking we shouldn't and its better off truncated, given as if it is a very long text, it will end up causing the candidate card to be immensely "tall"

**Comment by domlimm** [comment]
@charmainehly agreed!

**Comment by charmainehly** [comment]
to decide whether this is the expected error message - i.e. to prioritise office hours or candidate availabilities

<img width="1117" alt="Screenshot 2022-03-30 at 7 03 42 PM" src="https://user-images.githubusercontent.com/65525578/160819132-3662b3c7-3113-4ad1-aeb9-c4e8c69c4088.png">

**Comment by charmainehly** [comment]
Bug: @tiewweijian upon loading up the sample data, and immediately executing `delete 2` an error message pops up. the checks made in the code body in the following screenshot is likely erroneous?

<img width="896" alt="Screenshot 2022-03-30 at 7 18 05 PM" src="https://user-images.githubusercontent.com/65525578/160822766-3da836bc-ceb2-4979-9c11-a77c8722c356.png">

**Comment by charmainehly** [comment]
> Bug. Able to schedule interview outside of office hours.

Referencing the relevant code first --> should be able to port over this code lines into the `ScheduleEditCommand` class file to fix this issue

<img width="724" alt="Screenshot 2022-03-30 at 8 58 35 PM" src="https://user-images.githubusercontent.com/65525578/160839795-3fc3f964-be3d-47c3-aa79-88c516f2f847.png">

**Comment by lzan98** [comment]
> Bug. Able to schedule interview outside of office hours.
> 
> ![image](https://user-images.githubusercontent.com/77260893/160830016-676810b2-f87b-42ce-95ed-c8e32d09c244.png)

Same issue in schedule add command. Fixing it now.
<img width="1010" alt="Screenshot 2022-03-30 at 22 25 29" src="https://user-images.githubusercontent.com/66457036/160858284-b6d7ffa9-7ea4-49e5-959a-854d17647288.png">

**Comment by lzan98** [comment]
User input stays in the input box even after successful execution for schedule delete and schedule edit, but not schedule add.

<img width="1013" alt="Screenshot 2022-03-30 at 22 28 21" src="https://user-images.githubusercontent.com/66457036/160858892-3e41a245-3468-4ab8-b12e-26c704bfabcf.png">

**Comment by domlimm** [comment]
> User input stays in the input box even after successful execution for schedule delete and schedule edit.
> 
> <img alt="Screenshot 2022-03-30 at 22 28 21" width="1013" src="https://user-images.githubusercontent.com/66457036/160858892-3e41a245-3468-4ab8-b12e-26c704bfabcf.png">

I might not be following well but I thought this is the expected behaviour? Likewise from the other commands, as far as I'm aware!

**Comment by lzan98** [comment]
> > User input stays in the input box even after successful execution for schedule delete and schedule edit.
> > <img alt="Screenshot 2022-03-30 at 22 28 21" width="1013" src="https://user-images.githubusercontent.com/66457036/160858892-3e41a245-3468-4ab8-b12e-26c704bfabcf.png">
> 
> @lzan98 I might not be following well but I thought this is the expected behaviour? Likewise from the other commands, as far as I'm aware!

The expected behaviour the input is gone after successful execution! e.g. delete 2 -> afterwards the user input is no longer there!

**Comment by charmainehly** [comment]
> > > User input stays in the input box even after successful execution for schedule delete and schedule edit.
> > > <img alt="Screenshot 2022-03-30 at 22 28 21" width="1013" src="https://user-images.githubusercontent.com/66457036/160858892-3e41a245-3468-4ab8-b12e-26c704bfabcf.png">
> > 
> > 
> > @lzan98 I might not be following well but I thought this is the expected behaviour? Likewise from the other commands, as far as I'm aware!
> 
> The expected behaviour the input is gone after successful execution! e.g. delete 2 -> afterwards the user input is no longer there!

Huh that's weird, is there a sequence of steps you took to achieve this? as I tried executing schedule delete 2, and it works fine (i.e. the text input in the command box disappears)

**Comment by tiewweijian** [comment]
> 

Hey Charmaine ! I've fixed the bug and pushed up a new PR ! #250

**Comment by tiewweijian** [comment]
> Loading Data (see candidate at index 10:
> 
> * [ ]    if data loaded in has an empty string for `applicationStatus`, the tag does not show up.
> * [ ]    likewise with `interviewStatus`.
> 
> (ignore different coloured headers - not yet merged with latest pr standardising the ui)

Hey @charmainehly ! Could I check if you meant that when loading in without `ApplicationStatus` when we manually remove the `ApplicationStatus` and `InterviewStatus` from the JSON file?

**Comment by charmainehly** [comment]
> > Loading Data (see candidate at index 10:
> > 
> > * [ ]     if data loaded in has an empty string for `applicationStatus`, the tag does not show up.
> > * [ ]     likewise with `interviewStatus`.
> > 
> > (ignore different coloured headers - not yet merged with latest pr standardising the ui)
> 
> Hey @charmainehly ! Could I check if you meant that when loading in without `ApplicationStatus` when we manually remove the `ApplicationStatus` and `InterviewStatus` from the JSON file?

Yea! I'm guessing that @lzan98 's most recent forum clarification addresses this, and we can safely resolve this `bug`!

**Comment by tiewweijian** [comment]
> Yea! I'm guessing that @lzan98 's most recent forum clarification addresses this, and we can safely resolve this `bug`!

Sounds good ! I'll just add an emoji on the original thread to mark is as completed!

**Comment by tiewweijian** [comment]
![Screenshot 2022-03-31 at 1 20 46 AM](https://user-images.githubusercontent.com/34470525/160962131-98257608-12da-41cd-8311-04451dbe951f.png)

Just found a minor bug as well. 
After every command, the input box will be cleared for the next command. For `delete` command, the original command will still stay in the box. 

Might be affected by how I implemented the `Refresh` feature.

**Comment by lzan98** [comment]
Sm0l bug regarding the feedback after running edit/schedule edit

<img width="1189" alt="Screenshot 2022-03-30 at 2 51 43 PM" src="https://user-images.githubusercontent.com/66457036/160972903-5f564e7a-5c6c-425b-85dd-1354326a25bf.png">

**Comment by charmainehly** [comment]
Schedule add + all related commands:

**Comment by charmainehly** [comment]
filtered interview schedule refreshes unecessarily when editing remark of a candidate or editing a candidate:
1. view today
2. remark 1 r/change remark OR edit 1 n/change name
![Screenshot 2022-03-31 at 12 23 53 PM](https://user-images.githubusercontent.com/65525578/160976109-de3e35ed-39a3-4958-a508-7abede903e60.png)
![Screenshot 2022-03-31 at 12 24 22 PM](https://user-images.githubusercontent.com/65525578/160976155-343e129f-ccd3-433c-9623-0eeabf6a6d17.png)

suggested fix:
remove this line code from **BOTH** `remarkCommand` and `editCommand` files

![Screenshot 2022-03-31 at 12 26 33 PM](https://user-images.githubusercontent.com/65525578/160976467-9968e238-4ea7-4f96-998b-00b19bfcfd4d.png)

**Comment by charmainehly** [comment]
Buggy focus card profile photo:
![Screenshot 2022-03-31 at 12 27 24 PM](https://user-images.githubusercontent.com/65525578/160976568-b5346e28-9a5c-4518-93b2-36cc7d047646.png)

Attributed to calculation here:
![Screenshot 2022-03-31 at 12 28 01 PM](https://user-images.githubusercontent.com/65525578/160976649-473b6741-5820-46d3-8637-3f1622d949f7.png)

**Comment by charmainehly** [comment]
@tiewweijian  clear command not refreshing focus card to empty

![Screenshot 2022-03-31 at 12 54 56 PM](https://user-images.githubusercontent.com/65525578/160979391-c5bd64d1-70f2-4074-876f-47c6b0c9ba74.png)

**Comment by charmainehly** [comment]
@lzan98 not sure if should review the feedback messages displayed by `DeleteScheduleCommand` and `EditScheduleCommand`. Even if the `lastShownList` is empty, might not imply there are no interviews in the system.

**Comment by lzan98** [comment]
Steps taken to produce:

run `find k/nan k/name` to get 1 candidate in the filtered list

<img width="1189" alt="Screenshot 2022-03-30 at 2 51 43 PM" src="https://user-images.githubusercontent.com/66457036/160993141-b0a3abb5-3d22-4514-8638-dc4562707102.png">

`focus 1`to get Roy in the focus panel

<img width="1014" alt="Screenshot 2022-03-31 at 14 47 19" src="https://user-images.githubusercontent.com/66457036/160993293-b432bb19-f5ae-4b6d-aa10-4fa44482d810.png">

run `edit 1 n/baby` to edit Roy's name. Focus card changes to Alex upon execution -> most likely due to `updateFilteredCandidateList` being run.

<img width="1010" alt="Screenshot 2022-03-31 at 14 48 41" src="https://user-images.githubusercontent.com/66457036/160993530-604c82bc-7715-417d-9abf-8f6f4f23b607.png">

**Comment by lzan98** [comment]
//New issue instead after pulling latest change from master

Steps taken to produce:

run `find k/baby f/name` to get 1 candidate in the filtered list

<img width="1013" alt="Screenshot 2022-03-31 at 14 53 02" src="https://user-images.githubusercontent.com/66457036/160995167-0ef8650f-e672-42b7-8a12-05b19657249c.png">

run `focus 1`: No candidates displayed in focus

<img width="1013" alt="Screenshot 2022-03-31 at 14 53 32" src="https://user-images.githubusercontent.com/66457036/160995255-425239ae-a4d9-479c-8042-2a1782df1053.png">

**Comment by tiewweijian** [comment]
> Schedule add + all related commands: wrong feedback shown <img alt="Screenshot 2022-03-31 at 12 16 13 PM" width="1207" src="https://user-images.githubusercontent.com/65525578/160975394-32f1b8b0-37c9-4314-9074-a09cd646f755.png">
> 
> @tiewweijian

Hey @charmainehly i can't replicate this issue now ! I think moving the codes around for the other commands solved this issue too !

**Comment by charmainehly** [comment]
> > Schedule add + all related commands: wrong feedback shown <img alt="Screenshot 2022-03-31 at 12 16 13 PM" width="1207" src="https://user-images.githubusercontent.com/65525578/160975394-32f1b8b0-37c9-4314-9074-a09cd646f755.png">
> > @tiewweijian
> 
> Hey @charmainehly i can't replicate this issue now ! I think moving the codes around for the other commands solved this issue too !

replied you offline, sorry didn't include the exact command flow executed: 
1. focus 2
2. schedule add candidate/2 at/01-04-2022

**Comment by domlimm** [comment]
Found a bug:
When no interview scheduled i.e. interviews list empty, feedback message is as such `Interview date and time must be provided`

![image](https://user-images.githubusercontent.com/46486515/161060639-21b61d8b-9f44-43db-b04f-f389c22f402b.png)

**Comment by domlimm** [comment]
> > > User input stays in the input box even after successful execution for schedule delete and schedule edit.
> > > <img alt="Screenshot 2022-03-30 at 22 28 21" width="1013" src="https://user-images.githubusercontent.com/66457036/160858892-3e41a245-3468-4ab8-b12e-26c704bfabcf.png">
> > 
> > 
> > @lzan98 I might not be following well but I thought this is the expected behaviour? Likewise from the other commands, as far as I'm aware!
> 
> I think for the expected behaviour, the input is gone after successful execution! e.g. delete 2 -> afterwards the user input is no longer there!
> 
> @domlimm

I realised this only happen when no one is in focus i.e. no candidate is focused/candidate profile panel displays no candidate
