### ISSUE TITLE
Standardisation of feedback messages

### ISSUE THREAD

**Issue by charmainehly** [AY2122S2-CS2103-F11-2/tp#266]
Let's keep this thread open and add on any pointers for standardisation for different types of feedback messages. Shall we standardise invalid command results to the following format? (note the fullstop after the second line and after `Note:`)

I have fixed the wrapping of text in PR #265 

![Screenshot 2022-03-31 at 1 23 52 PM](https://user-images.githubusercontent.com/65525578/160982418-219cedae-436f-47f3-b370-a224ddea45be.png)

**Comment by tiewweijian** [comment]
![Screenshot 2022-03-31 at 1 52 16 PM](https://user-images.githubusercontent.com/34470525/160985671-3caa4cec-afd6-4bf3-8ada-34f3348f17e4.png)

Focus command is also in the incorrect format ! Will correct it now !

**Comment by charmainehly** [comment]
- [ ] focus
- [ ] help
- [ ] clear
- [ ] view
- [ ] exit
- [ ] list
- [ ] schedule (add, edit, delete)
- [ ] add
- [ ] delete
- [ ] edit
- [ ] remark
- [ ] find
- [ ] sort

**Comment by tiewweijian** [comment]
I marked out `focus`, `view` since we resolved it earlier! 
I marked out `exit` because I don't think there will be a feedback given to user. (Typing `exit uhnefwen`) still exits the system.
