### ISSUE TITLE
[PE-D] Fixed interview periods

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-F11-2/tp#317]
Limiting the interview period to 30 minutes is a *realistic* assumption, but limiting interview periods to fixed periods of 30 minutes may not best for the usability of the product.

Maybe some interviews would only take 15 minutes (short and sweet), or maybe some would take longer, like an hour or even longer.

## Suggestion
Allow users to customise the duration of an interview.

## Related Issue
See issue #3

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jamesyeap/ped#2

**Comment by domlimm** [comment]
Linked #321.
