### ISSUE TITLE
[PE-D] Restricting courses to only computing courses...

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-F11-2/tp#324]
... may limit the usage of the program for professors in general.

## Suggestion

As the user-guide specified the target-user to be professors in general (and not just professors in SoC), maybe this restriction can be lifted so other professors can also use this!

## Alternative
Another suggestion that I have would be to specify the target-audience more narrowly in the User-Guide (can say "...catered to professors **in the faculty of computing**..." in the first paragraph of the User-Guide) to help the course-restriction make sense in relation to the target-audience.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: jamesyeap/ped#5

**Comment by domlimm** [comment]
To update UG. Maybe have a section to address the courses we account for, similar to seniority.
