### ISSUE TITLE
[PE-D] [UG] Could use some diagrams

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-F11-2/tp#346]
Images could be used to show what the center panel is

![image.png](https://raw.githubusercontent.com/mazx4960/ped/main/files/8187958b-bf3c-4239-b083-bf9d48afcada.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: mazx4960/ped#11

**Comment by domlimm** [comment]
To take screenshot of command. Solely just the command.
