### ISSUE TITLE
[Bug] Interviews are automatically deleted at 31 minute mark instead of 30

### ISSUE THREAD

**Issue by lzan98** [AY2122S2-CS2103-F11-2/tp#363]
Currently, interviews are not deleted automatically from the interview schedule 30 minutes after an interview's start time (instead, they are deleted at the 31minute mark.) 
e.g. An interview that is scheduled at 5PM still exists in the interview schedule upon restarting the application at 5.30PM.

However, it should be deleted after 30 minutes instead, since an interview lasts for 30 minutes.
e.g. An interview that is scheduled at 5PM should not exist in the interview schedule upon restarting the application at 5.30PM.

This is a feature bug that affects our users as they would have expected the interview to be removed (and hence triggering an applicant's interview status to `Completed`) when restarting the application at 5.30PM.

**Comment by charmainehly** [comment]
@lzan98 @LeeEnEn  I don't think this is a bug that we will be allowed to fix. I believe we likely have to clarify within our UG. Don't think it is severe, as the 1 minute can be attributed to allow the clock to properly cross beyond the interview duration. E.g. interview from 9.30 to 10.00, then the interview only gets deleted at 10.01 .
