### ISSUE TITLE
Update DG - Model Component 

### ISSUE THREAD

**Issue by charmainehly** [AY2122S2-CS2103-F11-2/tp#393]
To update diagrams used [here](https://ay2122s2-cs2103-f11-2.github.io/tp/DeveloperGuide.html#model-component)

**Comment by domlimm** [comment]
@charmainehly might be overlapped with Issue #386 2nd task. Do you want me to do it instead?

Char maybe compare these 2 - [here](https://ay2122s2-cs2103-f11-2.github.io/tp/DeveloperGuide.html#model-component) and [here](https://ay2122s2-cs2103-f11-2.github.io/tp/DeveloperGuide.html#current-implementation).

Could use your inputs.

Thanks!

**Comment by charmainehly** [comment]
Ohh I see, sorry missed it out as thought that was just on the candidate model! :) let me close this. I have yet to start on this anyways!! 👍
