### ISSUE TITLE
Update DG - Common Classes

### ISSUE THREAD

**Issue by charmainehly** [AY2122S2-CS2103-F11-2/tp#395]
To add elaboration and update with any diagrams if needed [here](https://ay2122s2-cs2103-f11-2.github.io/tp/DeveloperGuide.html#common-classes)

**Comment by domlimm** [comment]
Hey @charmainehly, am suggesting to close this as I believe it's just a minor note. Checked some teams and past teams, no one changed it. If in agreement, can just close bah. Thanks! 😉
