### ISSUE TITLE
Update Developer Guide: User stories, Use cases, NFR and Glossary

### ISSUE THREAD

**Issue by charmainehly** [AY2122S2-CS2103-F11-2/tp#45]
Modify and refine the different sections in the developer guide to correct minor bugs.

- [x] Use cases: Standardise formatting for use cases (Add command)
- [x] Use cases: Standardise formatting for use cases (Delete command)
- [x] Use cases: Standardise formatting for use cases (List command)
- [x] Use cases: Standardise formatting for use cases (Find command)
- [x] Use cases: Standardise formatting for use cases (Help command)
- [x] User stories: Modify priority for "view all commands" from `medium` to `high`
- [x] NFR: Modify NFRs to be more specific and quantified
- [x] Glossary: Update glossary

**Comment by domlimm** [comment]
10/10 format HAHA love it.
