### ISSUE TITLE
Add confirmed interview slot for each candidate

### ISSUE THREAD

**Issue by charmainehly** [AY2122S2-CS2103-F11-2/tp#70]

**Comment by lzan98** [comment]
Hi @charmainehly ! I was thinking if we could push this to v1.3 instead because it is bit pointless to create this attribute without the scheduling function yet! 😅 What do you think?

**Comment by charmainehly** [comment]
Shifted to 1.3!!

**Comment by charmainehly** [comment]
Refer to #195
